# Generated by Django 4.0.1 on 2022-05-01 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto_Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.categoria')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.proyecto')),
            ],
        ),
    ]
