# Generated by Django 4.0.1 on 2022-05-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_presupuesto_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='presupuesto.proyecto'),
        ),
    ]
