# Generated by Django 4.0.1 on 2022-05-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_alter_presupuesto_proyecto_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presupuesto_proyecto',
            options={'ordering': ('-monto',)},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
