# Generated by Django 4.0.1 on 2022-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_alter_presupuesto_proyecto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.IntegerField(),
        ),
    ]
